# ===== Neon PostgreSQL Configuration =====
spring.datasource.url=jdbc:postgresql://ep-shiny-resonance-al8wifxv.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zvEAsB3oG7uN
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA Configuration =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT Configuration =====
jwt.secret=mySuperSecretKeyForJWTThatIsAtLeast256BitsLongForHS256Algorithm
jwt.expiration=86400000

# ===== Email Configuration (for 2FA) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=electroplanetaudit@gmail.com
spring.mail.password=msxrhkezvccyqwec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== File Upload Configuration =====
# Image upload config
file.upload-dir=uploads/images
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false